### ISSUE TITLE
BT/Wifi not working with downgrade patch on 4.81, CECH-2501B

### ISSUE THREAD

**Issue by cspencer49519** [Swizzy/PS3DumpChecker#12]
Hello, I tried to downgrade my CECH-2501B PS3 to 3.55 using the patcher included with the dump checker. Before patching, my BT/Wifi worked fine, after patching, it was not working. After several days, a lot of experimentation, and help from others, I ended up taking Rebug 4.81.2 REX and pulling it into PS3 MFX Builder, I then proceeded to patch BT/Wifi only, then I flashed the created PUP from the XMB. After doing this, my BT/Wifi returned.

**Comment by littlebalup** [comment]
You patched the Rebug 4.81.2 with no BT/Wifi patch then BT/Wifi World?? That have no sense.
Anyway the embeded patch is the Ferrox 4.81 coreOS. I never seen any issues about it.

**Comment by cspencer49519** [comment]
I know it sounds ridiculous, but this is what happened. I will try to be as thorough as I can in the following explanation.

I bought the console around 2011, it's a CECH-2501B, and it originally had firmware 3.40. I hacked the console at that point, but I'm not sure which firmware I used. The console remained on this hacked firmware until somewhere around 2013, when I let my little brother update the console so he could play COD online. The console remained in this unhacked state until last year. Sometime around the middle to end of last year I turned it on and updated it to 4.80, and attempted to pair my PS Vita to the console, I couldn't get it to pair, so I shut the console down. It remained on 4.80 until this year, when I soldered in a teensy++ and downgraded the console. This may be where I made the mistake. I used the PS3DumpChecker to patch my NOR dump, this patched my NOR dump for 4.81, maybe this caused the issue? After patching, I flashed the dump back to my PS3, and proceeded to attempt to install Rebug 4.81.2. The installation failed perpetually, and was giving me an error related to problems with the bluetooth/wifi. I asked for help in some forums, and a user there gave me a version of Rebug 4.81.2 that had the bluray, bluetooth, and wifi "drivers" removed. This finally allowed me to flash and I was able to get into the XMB. My PS3 remained like this for several days, I even ordered a 20' USB extension, thinking that my PS3 was going to be like this forever. I have several years of experience with modding consoles, but this is my first PS3. However, I was extremely confident that I had not caused any damage while inside the console, although people at the forums I was posting on were convinced otherwise. I tried several combinations of attempting to flash the full Rebug 4.81.2 from the XMB and recovery, nothing worked and I would always encounter the problem with BT/Wifi. I knew I at least had a good bluray drive, as it would read games, so on a whim I decided to take Rebug 4.81.2 and pull it into PS3 MFW builder, and just remove BT/wifi, leaving the bluray drivers. I did this, and then flashed the edited firmware to my console, upon reboot, my wifi/bluetooth worked again. This is about as concise as I can get, hope it makes sense. Maybe I should have upgraded the console to 4.81 before using a patch for 4.81? I patched my 4.80 console with the patches here, which are based on ferrox 4.81 correct?

**Comment by littlebalup** [comment]
No mater the patch you used. The only advantage to use a patch matching the installed OFW is to boot to xmb right after the flash.
So, your BT/wifi is not working, right? And the only way for you to install a fw is to remove the BT/wifi firmware from the pup. Means an hardware issue.

**Comment by cspencer49519** [comment]
No, my BT/Wifi is working fine now, but it was not after patching. I had to flash a firmware with disabled BT/wifi checks in order to get the firmware to install, then it started working again. I'm only posting this issue in order to help others whom may encounter the same problem.

**Comment by littlebalup** [comment]
It may be BT/wifi firmware write error where the read is OK. Just assumption.
Try to re-install the original rebug 4.81.2 a second time. If you have the same problem, it will confirm hardware issue as the initial patch is fully overwriten once a CFW is installed.
