### ISSUE TITLE
Unhandled Exception at Launch

### ISSUE THREAD

**Issue by arman-ku** [Swizzy/PS3DumpChecker#15]
Happens at each launch no matter what. win10pro x64 10.0.17134.228
[uexc.txt](https://github.com/Swizzy/PS3DumpChecker/files/2339468/uexc.txt)

**Comment by arman-ku** [comment]
i am having another issue but i think it happens because of this one. ps3dumpchecker seems to patch the images incorrectly. i can see the ROS being patched, but when i load the patched backup, it does not get detected as prepatched, so i get asked if i want to patch again.

**Comment by Swizzy** [comment]
It means your hashes aren’t up to date or the guy that maintains this now forgot to update that

________________________________

**Comment by arman-ku** [comment]
I am using the one provided in this repo. Just cloned it again just to be sure. Still same.

**Comment by littlebalup** [comment]
The guy is still around ;)
I double checked and everything works fine for me on Win10 Pro x64 10.0.17134.

You can check those points:
- Ensure .NET Framework 3.5 is correctly installed and activated: https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10
- Run the exe as administrator.
- Deactivate your antivirus.

**Comment by arman-ku** [comment]
Thank you.

Are you sure the image patch bug is caused by this as well?
It is a completely original bin with ofw ROS.
I tried it with a ps3xploit patched image too, same.

**Comment by littlebalup** [comment]
No, it's not caused by that. I feel your hashlist is no updated. Ensure you have the latest version (build 491 or 492) and delete any default.hashlist and default.cfg file from your exe folder (so, they will be regenerated with latest versions included in the exe). Then try again please.

**Comment by littlebalup** [comment]
@Swizzy, could you help on that?
That error appears at launch when one or both of the "Enable auto cfg download" or "Enable auto hashlist download " options are checked or when openning the UpdateForm. Same issue on both Win10 and 7. Same issue with previous builds that worked before. 
I feel something changed on the github side but I fail to identify what's wrong... :(

**Comment by Swizzy** [comment]
Where is it crashing exactly?

**Comment by littlebalup** [comment]
Each time the app try to connect to your github repo to download string or file. This is an example of the catched webexception from the UpdateForm GetFinalUrl fonction  : https://image.prntscr.com/image/Tw7dvfI0TRuHef6f9WymJA.png

**Comment by littlebalup** [comment]
Well, I think I finally found someting... 
Seems github moved to TLS 1.2 security protocol : https://www.ssllabs.com/ssltest/analyze.html?d=github.com&s=192.30.253.112&hideResults=on
And that protocol is not supported by .Net framework 2.0...
Changing to .Net framework 4.5 and using "ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;" before a HttpWebRequest seems to work.

**Comment by Swizzy** [comment]
Makes sense, the original error doesn't say that specifically tho :/

There are workarounds - for example using another server that communicates with Github instead of the app communicating with github...

**Comment by littlebalup** [comment]
Well, I personnaly don't want to mess with another server... And  I think we can definitivelly move to .Net 4.5 now. I made the changes and it's ready to commit. Just let me know if you disagree.

**Comment by littlebalup** [comment]
https://github.com/Swizzy/PS3DumpChecker/commit/d9d827c9befa73289601c8e1ec01c22efa398a4d
